-- SQL Schema Initialization for Auth Service (users table)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

-- Seed default admin user (Password: admin123, BCrypt encoded)
INSERT INTO users (username, email, password, role)
VALUES ('admin', 'admin@cloudstore.com', '$2a$10$eD2B6aP3U4X5Z6Y7W8V9U.1234567890abcdefghijklmnopqrstuvw', 'ROLE_ADMIN')
ON CONFLICT (username) DO NOTHING;
