server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Enable Resilience4j Circuit Breaker for OpenFeign Clients
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

# Resilience4j Circuit Breaker & Rate Limiter Configurations
resilience4j:
  circuitbreaker:
    instances:
      authServiceClient:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms

# Spring Boot Actuator Monitoring Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
